FROM node:14.18.1-stretch

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY ./src/package*.json ./
RUN npm install

# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
COPY ./src .

# Expose port 3000 and start php-fpm server
EXPOSE 3000
CMD [ "node", "app.js" ]